config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root 'articles#index'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  scope :recent, -> { order(created_at: :desc) }
  enum status: { draft: 0, publish: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    member: 0,
    admin: 10
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_article, only: [:edit, :update, :destroy, :show]
  before_action :find_options_for_article_status, only: [:new, :edit]

  def index
    @articles = Article.publish.recent
  end

  def new
    @article = Article.new
  end

  def show; end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path
    else
      render :edit
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to edit_article_path(@article), notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    # ToDo: 改用軟刪除
    redirect_to articles_path, notice: '已成功刪除' if @article.destroy
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(
      :title,
      :content,
      :status
    )
  end

  def find_options_for_article_status
    @options_for_article_status = Article.statuses.map do |key, _|
      [I18n.t(key, scope: 'enum.article.status'), key]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def markdown(text)
    render_options = {
      filter_html: true,
      hard_wrap: true,
      prettify: true,
      link_attributes: {
        rel: 'nofollow noopener',
        target: '_blank'
       }
    }

    markdown_options = {
      autolink: true,
      fenced_code_blocks: true,
      highlight: true,
      no_intra_emphasis: true,
      strikethrough: true,
      space_after_headers: true,
      superscript: true
    }

    rendered =  SyntaxHighlightHtml.new(render_options)
    markdown = Redcarpet::Markdown.new(rendered, markdown_options)
    markdown.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="mx-5">
  <%= form_for article do |f| %>

    <div class="form-group">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content, class: 'form-label' %>
      <%= f.text_area :content, class: 'form-control', style: 'height: 300px' %>
    </div>

    <div class="form-group">
      <%= f.label :status, class: 'form-label' %>
      <%= f.select :status, options_for_select(@options_for_article_status, article.status), {}, { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= f.submit '儲存', class: 'btn btn-dark btn-sm' %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="mx-5 my-3">
  編輯文章
</div>

<%= render partial: 'form', locals: { article: @article } %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @articles.each do |article| %>
        <div class="post-preview">
          <%= link_to article_path(article) do %>
            <h2><%= article.title %></h2>
          <% end %>
          <p class="post-meta">
            <%= article.created_at.strftime('Posted on %F') %>
          </p>
        </div>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to '編輯', edit_article_path(article) %>
          <%= link_to '刪除', article_path(article), method: 'delete', data: { confirm: '確定要刪除？' } %>
        <% end %>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-5 my-3">
  新增文章
</div>

<%= render partial: 'form', locals: { article: @article } %>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-preview">
        <h2><%= @article.title %></h2>
        <p class="post-meta">
          <%= @article.created_at.strftime('Posted on %F') %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to 'Edit', edit_article_path(@article), class: 'ml-2' %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <article>
          <p>
            <%= markdown(@article.content) %>
          </p>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <%= link_to 'https://twitter.com/lynnchang1004', target: '_blank' do %>
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
            </a>
          </li>
          <li class="list-inline-item">
            <%= link_to 'https://twitter.com/lynnchang1004', target: '_blank' do %>
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
            </a>
          </li>
          <li class="list-inline-item">
            <%= link_to 'mailto:tv725987@gmail.com', target: '_blank' do %>
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fas fa-envelope fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">
          Copyright &copy; Lynn's Dev Blog <%= Time.zone.now.year %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Lynn's Dev Blog</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'About', '#', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Posts', articles_path, class: 'nav-link' %>
        </li>

        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Add article', new_article_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'logout', destroy_user_session_path, class: 'nav-link', method: 'delete' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'login', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<header class="masthead">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h2>
            Lynn's Dev Blog
          </h2>
          <span class="subheading">
            Step by step. Enjoying what coding gives me.
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lynn's Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>